name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  device:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.5
        bundler-cache: true
        working-directory: device
    - run: |
        cd device
        bundle exec foodcritic cookbooks/munger
        bundle exec kitchen verify
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build server
